### ISSUE TITLE
hover behavior for book icons throughout

### ISSUE THREAD

**Issue by ian-crowther** [Hederis/hederis.github.io#13]
https://www.dropbox.com/s/u17wcgh5zmzixzo/Screenshot%202018-09-30%2013.37.41.png?dl=0

If there's time and energy available, I'd love to have some kind of css-animated open/close hover effect on the book icon used throughout the site - I think it would be especially effective on the pricing page, where there's so many of them. 

Similar to what I'd proposed for the book in the hero space at the top of the homepage, but on hover and with some (brief) duration and easing to it so that we could have something that looks a bit intricate here when the user hovers over a few of the books in sequence.

**Comment by EricWVGG** [comment]
I recall this request from the original spec and I'm still not sure what icon you're referring to. Can I see a dumb screenshot or something?

**Comment by ian-crowther** [comment]
There's a screenshot link in my original issue message. here it is uploaded:
<img width="1005" alt="screenshot 2018-09-30 13 37 41" src="https://user-images.githubusercontent.com/4146556/46302386-e8f54100-c576-11e8-9b21-6df790c3626c.png">

**Comment by EricWVGG** [comment]
I see. Sure, no problem

**Comment by ian-crowther** [comment]
@EricWVGG I'm not seeing this on the pricing page, so reopening. It remains an enhancement, though, not a bug.

**Comment by EricWVGG** [comment]
oh, it was in icon.html, I didn't even know about the pricing page. Moved.
