### ISSUE TITLE
book frame border

### ISSUE THREAD

**Issue by ian-crowther** [Hederis/hederis.github.io#14]
https://www.dropbox.com/s/mxzajg51mz5keth/Screenshot%202018-09-30%2013.45.07.png?dl=0

Eric, I think I may have answered your question from Slack a few days back incorrectly. There should be a border around the book frame but the appearance of it on Nellie's branch just wasn't quite right - I had thought that appearance was coming from an iframe border inadequately hidden. I added an issue for @nelliemckesson to address that.

**Comment by EricWVGG** [comment]
rolling this into #15
