### ISSUE TITLE
size/shape of book frame

### ISSUE THREAD

**Issue by ian-crowther** [Hederis/hederis.github.io#15]
https://www.dropbox.com/s/mxzajg51mz5keth/Screenshot%202018-09-30%2013.45.07.png?dl=0

Looks like on this branch, the book frame extends all the way to the bottom of the viewport, but it should be offset as on the main V2.

**Comment by EricWVGG** [comment]
I can restore that behavior, but I warn you guys that it's never going to work very well.

**Comment by ian-crowther** [comment]
Would you mind explaining in a little more detail? Maybe there's another way to solve the issue.

**Comment by EricWVGG** [comment]
It's difficult to explain in detail, but basically what you're trying to do is hijack the browser's scrolling behavior, and that always, always winds up being janky.

**Comment by EricWVGG** [comment]
yeah, like I could add a mask at the bottom… I don't really understand the metaphor, though; pages don't flip, they scroll. Unless you're on a good e-reader and replace flipping with scrolling — and we've already got scrolling. That's just how digital screens work.

**Comment by EricWVGG** [comment]
re: Ian “Eric, I think I may have answered your question from Slack a few days back incorrectly. There should be a border around the book frame but the appearance of it on Nellie's branch just wasn't quite right - I had thought that appearance was coming from an iframe border inadequately hidden. I added an issue for @nelliemckesson to address that.”

**Comment by EricWVGG** [comment]
restored

**Comment by nelliemckesson** [comment]
@EricWVGG @ian-crowther Just want to check in on where we landed on this. In the v2-eric branch, it looks like the bookframe still stretches the full window height. Are we sticking with that behavior?

![screen shot 2018-10-09 at 10 58 13 pm](https://user-images.githubusercontent.com/812739/46715974-12693900-cc17-11e8-86c7-b8b92c03b28d.png)

**Comment by EricWVGG** [comment]
Yup I forgot to push out a branch. Take another look.
