### ISSUE TITLE
Color of border around book frame

### ISSUE THREAD

**Issue by ian-crowther** [Hederis/hederis.github.io#2]
https://www.dropbox.com/s/yi1wgg99lphid85/Screenshot%202018-09-30%2012.29.10.png?dl=0

Should be: #585162 or rgb(88,81,98)

**Comment by nelliemckesson** [comment]
@EricWVGG curious if there's a reason you went with _outline_ for the bookframe border vs. _border_. Will changing it back to _border_ mess up any of the effects? (The design calls for a slight rounded corner on the left-side corners)

**Comment by EricWVGG** [comment]
No that was an oversight.
