### ISSUE TITLE
flow chart: scroll speed

### ISSUE THREAD

**Issue by ian-crowther** [Hederis/hederis.github.io#20]
Eric, one general note on the flow chart animations - they look absolutely tremendous, but would it be possible to slow down the speed that everything occurs (other than the background rotating, perhaps) to 75% or 50% of the scroll speed? I think we'll still have the rotating background to make it clear to people that the screen hasn't frozen and the site hasn't broken.

Suggested approaches: 

1. just make everything react 25-50% slower
2. have every element keep the same speed it has now, but with waypoints further apart - not corresponding to actual points on the page scroll, but like, 50-100% past them.

This is where my ability to parse the interactivity starts to fall down, so I'm completely open to your feedback on this issue, but I do think we need some way to address that someone quickly scrolling through the content of the page is likely to miss some of the intricacy of this section, and if there's a way to manage that through some durational modifications to the JS, that would be great.

**Comment by EricWVGG** [comment]
Did both.
