### ISSUE TITLE
alignment and appearance of unordered list items

### ISSUE THREAD

**Issue by ian-crowther** [Hederis/hederis.github.io#23]
https://www.dropbox.com/s/8zimvuj0iwnqg2c/Screenshot%202018-09-30%2014.19.56.png?dl=0

- [ ] Bullets should be diamond shaped
- [ ] ideally the bullets should be aligned so that they're flush left with the text block they follow.

**Comment by nelliemckesson** [comment]
@ian-crowther can you send me an image file for the diamond?
