### ISSUE TITLE
Type size throughout

### ISSUE THREAD

**Issue by ian-crowther** [Hederis/hederis.github.io#8]
I don't have a specific screenshot for this, but it looks like the type sizing throughout is too small.

@nelliemckesson were you taking sizes from the mobile comps? 

Let me know what I can do to help address this.

**Comment by ian-crowther** [comment]
For example, body text size on desktop should be consistently 24 with a line-height: 1.3333 but is currently 21/line-height: 1.476 in the book frame and 17 with a line-height: 1.485714286 elsewhere.

**Comment by ian-crowther** [comment]
Ideally, we'd get to a point where we have some specific sizing for known breakpoints, rather than having text be the same size regardless of viewport size. This might be something you and I can circle back on later, @nelliemckesson

**Comment by nelliemckesson** [comment]
Ah yeah, I actually sized it down while I was putting things together, because some of the text just looked really big when I was previewing. I went ahead and sized it up a little bit more.
